config/routes.rb
Rails.application.routes.draw do

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :api do

    scope '/java', defaults: { format: :json } do
      post 'login_user', to: 'selenium#login_user'
      get 'get_scheduler', to: 'selenium#get_scheduler'
      get 'software_version', to: 'selenium#software_version'

      get 'get_projects', to: 'selenium#get_projects'
      get 'get_environments', to: 'selenium#get_environments'
      get 'get_environment', to: 'selenium#get_environment'
      get 'get_custom_command', to: 'selenium#get_custom_commands'

      get 'get_test_suites', to: 'selenium#get_test_suites'
      get 'get_test_suite', to: 'selenium#get_test_suite'
      post 'schedule_test_suite', to: 'selenium#schedule_test_suite'
      get 'unschedule_test_suite', to: 'selenium#unschedule_test_suite'

      get 'get_all_test_cases', to: 'selenium#get_test_cases'

      post 'create_result_suite', to: 'selenium#create_result_suite'
      post 'create_result_case', to: 'selenium#create_result_case'
      post 'update_result_suite', to: 'selenium#update_result_suite'
      post 'update_scheduler_status', to: 'selenium#update_scheduler_status'
      post 'upload_video', to: 'selenium#upload_video'
      post 'upload_screenshot', to: 'selenium#upload_screenshot'
    end

    namespace :v1 do
      resources :projects, only: [:index]

      resources :environments, only: [:index] do
        resources :test_suites, only: [:index, :create] do
          resources :test_cases, only: [:index, :create, :show, :update]
          resources :manual_test_cases, only: [:index, :create, :show, :update]
        end
        resources :custom_commands, only: [:index]
      end

      resources :users, only: [:index] do
        collection do
          post :login
          get :logout
        end
      end
    end
  end
  #end of api namespace

  resources :projects do
    collection do
      get :get_environments
    end
    resources :team_members do
      collection do
        post :assign_existing_member
      end
    end
  end

  resources :environments do
    member do
      get :login_details
      post :login_details

      get :git_branch_details
      post :git_branch_details
    end
    resources :custom_commands
    resources :test_plans do
      collection do
        get :flow_states
        get :hierarchy
        post :hierarchy
        get :load_plan_tree
      end
    end
    resources :test_roles

    resources :test_suites do
      member do
        get :assign_users
        post :assign_users
        get :remove_assign_suite
      end

      collection do
        get :import
        post :import
        get :automated
      end

      resources :test_cases do
        collection do
          get :selenium_custom_code
          get :export
        end
      end

      resources :manual_test_cases do
        member do
          delete :delete_attachment
        end
      end

      resources :schedulers do
        resources :results, only: [:index, :update] do
          member do
            get :status_override
          end
          collection do
            get :mark_as_demo_video
            get :download_results
            post :upload_recording
            get :delete_recording
          end
        end
      end

      resources :periodics
    end
  end

  resources :assign_suites, only: [:index] do
    collection do
      get :manual
    end
    member do
      get :manual_cases
    end
  end

  resources :manual_case_results do
  end

  resources :suite_reports, only:[:index, :show] do
    collection do
      get :automated
    end
  end
  resources :software_versions

  resource :session, only: [:create, :destroy] do
    collection do
      get :login
    end
  end

  resources :users, only: [:edit, :update] do
    member do
      get :settings
      post :settings
      delete :remove_invitation
      get :resend_invitation
    end
    collection do
      get :invite
      post :invite
      get :accept_invitation
      get :forgot_password
      post :forgot_password
      get :reset_password
    end
  end

  match "suites", to: "test_suites#suites", via: [:get]
  match "load_image", to: "file_handler#load_image", via: [:get]
  match "load_video", to: "file_handler#load_video", via: [:get]
  match "fetch-team-members", to: "team_members#fetch_team_members", via: [:get, :post]
  match "privacy_policy", to: "home#privacy_policy", via: :get
  match "documentation", to: "home#documentation", via: :get
  match "project_roles", to: "roles#project_roles", via: :get, as: "access_roles"

  # Defines the root path route ("/")
  #
  root "home#index"
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :get_project, except: [:fetch_team_members]
  before_action :get_user, only: %i[show edit update]

  def index
    @project_users = User.joins(:project_team_members).select('users.*,project_team_members.id as ptm').where('project_team_members.project_id': params[:project_id]).uniq
  end

  def new
    @user = User.new
  end

  #this method is not being used any more - it was written to invite external user
  # Logic has shifted while assign manual suite to user
  def create
    @user = User.new(team_member_params)
    @user.project_id = @project.id
    @user.allow_generate_password = true
    if @user.save
      flash[:success] = 'User has been assigned to project.'
      redirect_to project_team_members_url(@project)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(team_member_params)
      flash[:success] = 'Tem member has been updated.'
      redirect_to project_team_members_url(@project)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end
  def destroy
    project_team_member = ProjectTeamMember.where(id: params[:id]).take
    if project_team_member.destroy
      flash[:success] = 'Team member has been deleted from project successfully.'
    else
      flash[:errors] = project_team_member.errors.full_messages
    end
    redirect_to project_team_members_url
  end

  def assign_existing_member
    @user = User.new
    user = User.where(email: team_member_params[:email]).take
    project_team_member = ProjectTeamMember.find_or_initialize_by(team_member: user, project: @project)
    if user and project_team_member.valid?
      project_team_member.save
      flash[:success] = 'User has been assigned to project.'
      redirect_to project_team_members_url(@project)
    else
      flash.now[:errors] = "Email can't be blank."
      render :new
    end
  end

  def fetch_team_members
    users = User.where("first_name like ? OR last_name like ? OR email like ?", "#{params[:term]}%", "#{params[:term]}%", "#{params[:term]}%")
    if params[:format_id]
      render json: {results: users.collect{|user| {id: user.id, text: "#{user.full_name} <#{user.email}> "}}}
    else
      render json: {results: users.collect{|user| {id: user.email, text: "#{user.full_name} <#{user.email}> "}}}
    end
  end

  private

  def get_project
    @project = Project.find(params[:project_id])
  end

  def get_user
    @user = User.find(params[:id])
  end

  def team_member_params
    params.require(:user).permit(:first_name, :last_name, :email, :project_id, :project_access_role_id)
  end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_form.html.erb
<%= render partial: 'layouts/flash_message' %>
<div class="row">
  <% if @user.id.blank? %>
    <div class="col-md-12">
      <p class="text-theme fs-5">Assign Existing Member</p>
      <%#= form_with model: @user, url: @user.new_record? ? project_team_members_path(@project, @user) : project_team_member_path(@project, @user), data: { turbo: false } do |f| %>
       <%= form_tag assign_existing_member_project_team_members_path(@project), data: { turbo: false } do %>
        <div class="row g-3">

          <div class="col-md-12">
            <label class="form-label fw-bold" for="user_project_id">Project:</label>
            <%= select_tag(:project_id, options_for_select([[@project.name, @project.id]]), name: 'user[project_id]', id:'user_project_id', class: "form-control", multiple: false) %>
          </div>

          <div class="col-md-12">
            <label class="form-label fw-bold" for="user_email">Email:</label>
            <%= select_tag(:email, options_for_select([]), name: 'user[email]', id:'user_email', class: "form-control", multiple: false) %>
          </div>

          <div class="col-md-12">
            <%#= f.hidden_field :project_id, value: @project.id %>
            <%= submit_tag "Submit", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

</div>

<script type="application/javascript">
    <% if @user.id.blank? %>
    $('#user_email').select2({
        theme: "bootstrap",
        placeholder: "Search and select team member by name",
        width: '100%',
        multiple: false,
        ajax: {
            url: '<%= fetch_team_members_path(format: :json) %>',
            dataType: 'json'
        }
    })
    <% end %>
</script>

app/views/team_members/edit.html.erb
<%
  breadcrumb = {'Home': root_url, 'Manage Projects' => projects_url , 'Manage Team Members' => project_team_members_url(@project), 'Update Team Member' => '#' }
  btns = []
%>
<%= render partial: 'common/breadcrumb', locals: {heading: 'Edit Assign User', breadcrumb: breadcrumb, action_btns: btns} %>
<section class="section min-vh-100">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <div class="mt-3">
            <%= render partial: 'team_members/form' %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/team_members/index.html.erb
<%
  breadcrumb = {'Home': root_url, 'Manage Projects' => projects_url , 'Manage Team Members' => project_team_members_url(@project) }
  btn = [{name: 'Assign Member', url: new_project_team_member_path(@project), class: 'btn btn-primary btn-sm float-right'}]
%>
<%= render partial: 'common/breadcrumb', locals: {heading: 'Manage Team Members', breadcrumb: breadcrumb, action_btns: btn} %>

<section class="section min-vh-100">

  <%= render partial: 'layouts/flash_message' %>
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <p class="card-title">Project: <%= @project.name %></p>
          <!-- Table with stripped rows -->
          <table class="table datatable mt-2">
            <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th data-type="date" data-format="DD-MM-YYYY">Created</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <% if @project_users %>
              <% @project_users.each do |project_user| %>
                <tr>
                  <td><%= project_user.full_name  %></td>
                  <td><%= project_user.email %></td>
                  <td><%= date_format(project_user.created_at) %></td>
                  <td>
                    <%= link_to(project_team_member_path(@project, project_user.ptm), method: :delete, data: {confirm: 'Are you sure?'}, title: 'Delete Project') do %>
                      <i class="bi bi-trash"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
            </tbody>
          </table>
          <!-- End Table with stripped rows -->

        </div>
      </div>

    </div>
  </div>
</section>

app/views/team_members/new.html.erb
<%
  breadcrumb = {'Home': root_url, 'Manage Projects' => projects_url , 'Manage Team Members' => project_team_members_url(@project), 'Assign Team Member' => '#' }
  btns = []
%>
<%= render partial: 'common/breadcrumb', locals: {heading: 'Create Team Member', breadcrumb: breadcrumb, action_btns: btns} %>
<section class="section min-vh-100">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <div class="mt-3">
            <%= render partial: 'team_members/form' %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>