config/routes.rb
Rails.application.routes.draw do

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :api do

    scope '/java', defaults: { format: :json } do
      post 'login_user', to: 'selenium#login_user'
      get 'get_scheduler', to: 'selenium#get_scheduler'
      get 'software_version', to: 'selenium#software_version'

      get 'get_projects', to: 'selenium#get_projects'
      get 'get_environments', to: 'selenium#get_environments'
      get 'get_environment', to: 'selenium#get_environment'
      get 'get_custom_command', to: 'selenium#get_custom_commands'

      get 'get_test_suites', to: 'selenium#get_test_suites'
      get 'get_test_suite', to: 'selenium#get_test_suite'
      post 'schedule_test_suite', to: 'selenium#schedule_test_suite'
      get 'unschedule_test_suite', to: 'selenium#unschedule_test_suite'

      get 'get_all_test_cases', to: 'selenium#get_test_cases'

      post 'create_result_suite', to: 'selenium#create_result_suite'
      post 'create_result_case', to: 'selenium#create_result_case'
      post 'update_result_suite', to: 'selenium#update_result_suite'
      post 'update_scheduler_status', to: 'selenium#update_scheduler_status'
      post 'upload_video', to: 'selenium#upload_video'
      post 'upload_screenshot', to: 'selenium#upload_screenshot'
    end

    namespace :v1 do
      resources :projects, only: [:index]

      resources :environments, only: [:index] do
        resources :test_suites, only: [:index, :create] do
          resources :test_cases, only: [:index, :create, :show, :update]
          resources :manual_test_cases, only: [:index, :create, :show, :update]
        end
        resources :custom_commands, only: [:index]
      end

      resources :users, only: [:index] do
        collection do
          post :login
          get :logout
        end
      end
    end
  end
  #end of api namespace

  resources :projects do
    collection do
      get :get_environments
    end
    resources :team_members do
      collection do
        post :assign_existing_member
      end
    end
  end

  resources :environments do
    member do
      get :login_details
      post :login_details

      get :git_branch_details
      post :git_branch_details
    end
    resources :custom_commands
    resources :test_plans do
      collection do
        get :flow_states
        get :hierarchy
        post :hierarchy
        get :load_plan_tree
      end
    end
    resources :test_roles

    resources :test_suites do
      member do
        get :assign_users
        post :assign_users
        get :remove_assign_suite
      end

      collection do
        get :import
        post :import
        get :automated
      end

      resources :test_cases do
        collection do
          get :selenium_custom_code
          get :export
        end
      end

      resources :manual_test_cases do
        member do
          delete :delete_attachment
        end
      end

      resources :schedulers do
        resources :results, only: [:index, :update] do
          member do
            get :status_override
          end
          collection do
            get :mark_as_demo_video
            get :download_results
            post :upload_recording
            get :delete_recording
          end
        end
      end

      resources :periodics
    end
  end

  resources :assign_suites, only: [:index] do
    collection do
      get :manual
    end
    member do
      get :manual_cases
    end
  end

  resources :manual_case_results do
  end

  resources :suite_reports, only:[:index, :show] do
    collection do
      get :automated
    end
  end
  resources :software_versions

  resource :session, only: [:create, :destroy] do
    collection do
      get :login
    end
  end

  resources :users, only: [:edit, :update] do
    member do
      get :settings
      post :settings
      delete :remove_invitation
      get :resend_invitation
    end
    collection do
      get :invite
      post :invite
      get :accept_invitation
      get :forgot_password
      post :forgot_password
      get :reset_password
    end
  end

  match "suites", to: "test_suites#suites", via: [:get]
  match "load_image", to: "file_handler#load_image", via: [:get]
  match "load_video", to: "file_handler#load_video", via: [:get]
  match "fetch-team-members", to: "team_members#fetch_team_members", via: [:get, :post]
  match "privacy_policy", to: "home#privacy_policy", via: :get
  match "documentation", to: "home#documentation", via: :get
  match "project_roles", to: "roles#project_roles", via: :get, as: "access_roles"

  # Defines the root path route ("/")
  #
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :restricted_to_sign_in_user, only: [:privacy_policy]
  before_action :user_projects, except: [:privacy_policy]

  def index
    @environments = Environment.where(project_id: @projects.collect(&:id))
    @test_suites = TestSuite.where(environment_id: @environments.collect(&:id))
    @test_cases = TestCase.where(test_suite_id: @test_suites.collect(&:id))
    @manual_cases = ManualCase.where(test_suite_id: @test_suites.collect(&:id))

    @scheduler_success = @test_suites.collect{|ts| ts.schedulers.where(status: Scheduler::SUCCESS_STATUS).count}.compact.sum
    @scheduler_ready = @test_suites.collect{|ts| ts.schedulers.where(status: Scheduler::READY_STATUS).count}.compact.sum
    @scheduler_error = @test_suites.collect{|ts| ts.schedulers.where(status: Scheduler::ERROR_STATUS).count}.compact.sum
    @scheduler_running = @test_suites.collect{|ts| ts.schedulers.where(status: Scheduler::RUNNING_STATUS).count}.compact.sum
    @scheduler_complete = @test_suites.collect{|ts| ts.schedulers.where(status: Scheduler::COMPLETE_STATUS).count}.compact.sum

    @browsers = Scheduler.select('browser_id').group(:browser_id).count

    @recent_schedulers = Scheduler.order('updated_at DESC').limit(5)
    @manual_test_suites = @test_suites.where(is_automated: false)
    @automate_test_suites = @test_suites.where(is_automated: true)

    @recorded = Scheduler.where(record_session: true).count
    @non_recorded = Scheduler.where(record_session: false).count
  end

  def privacy_policy
  end

  def documentation
    @versions = SoftwareVersion.order(release_date: :desc)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_recent_schedulers.html.erb
<div class="col-12">
  <div class="card recent-sales overflow-auto">

    <!--    <div class="filter">-->
    <!--      <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>-->
    <!--      <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">-->
    <!--        <li class="dropdown-header text-start">-->
    <!--          <h6>Filter</h6>-->
    <!--        </li>-->

    <!--        <li><a class="dropdown-item" href="#">Today</a></li>-->
    <!--        <li><a class="dropdown-item" href="#">This Month</a></li>-->
    <!--        <li><a class="dropdown-item" href="#">This Year</a></li>-->
    <!--      </ul>-->
    <!--    </div>-->

    <div class="card-body">
      <h5 class="card-title">Recent Scheduler(s)</h5>

      <table class="table table-borderless datatable">
        <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Suite</th>
          <th scope="col">Browser</th>
          <th scope="col">Tester</th>
          <th scope="col">Scheduled</th>
          <th scope="col">Status</th>
        </tr>
        </thead>
        <tbody>
        <% @recent_schedulers.each do |recent_scheduler| %>
          <tr>
            <th scope="row">
              <% if recent_scheduler.status.downcase == Scheduler::READY_STATUS.downcase %>
                #<%= recent_scheduler.id %>
              <% else %>
                <a href="<%= environment_test_suite_scheduler_results_path(recent_scheduler.test_suite.environment, recent_scheduler.test_suite, recent_scheduler) %>" target="_blank">
                  #<%= recent_scheduler.id %>
                </a>
              <% end %>
            </th>
            <td><%= recent_scheduler.test_suite.name %></td>
            <td><%= Browser::BROWSERS.invert[recent_scheduler.browser_id] %></td>
            <td><%= user_full_name(recent_scheduler.user) %></td>
            <td><%= recent_scheduler.scheduled_date.strftime('%Y-%m-%d %H:%m') %></td>
            <td><%= render partial: "schedulers/status", locals: {scheduler: recent_scheduler} %></td>
          </tr>
        <% end %>

        </tbody>
      </table>

    </div>

  </div>
</div>

app/views/home/_record_session_chart.html.erb
<div class="card">
  <!--        <div class="filter">-->
  <!--          <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>-->
  <!--          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">-->
  <!--            <li class="dropdown-header text-start">-->
  <!--              <h6>Filter</h6>-->
  <!--            </li>-->

  <!--            <li><a class="dropdown-item" href="#">Today</a></li>-->
  <!--            <li><a class="dropdown-item" href="#">This Month</a></li>-->
  <!--            <li><a class="dropdown-item" href="#">This Year</a></li>-->
  <!--          </ul>-->
  <!--        </div>-->

  <div class="card-body pb-0">
    <h5 class="card-title">Suite Record Sessions</h5>

    <div id="suiteRecording"></div>

    <script>
        //document.addEventListener("DOMContentLoaded", () => {
        var chart = new ApexCharts(document.querySelector("#suiteRecording"), {
            series: [{
                data: [<%= @recorded %>, <%= @non_recorded %>]
            }],
            chart: {
                type: 'bar',
                height: 180
            },
            plotOptions: {
                bar: {
                    borderRadius: 4,
                    horizontal: false,
                }
            },
            dataLabels: {
                enabled: true,
            },

            xaxis: {
                categories: ['Recorded', 'Non-Recorded'],
            }
        }).render();
        //});
    </script>

  </div>
</div>

app/views/home/_suite_browser_status.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Suite Scheduler Browsers Chart</h5>

    <!-- Bar Chart -->
    <canvas id="barChart1" style="max-height: 400px;"></canvas>
    <script>
        //document.addEventListener("DOMContentLoaded", () => {
            new Chart(document.querySelector('#barChart1'), {
                type: 'bar',
                height: 350,
                data: {
                    labels: ['Chrome', 'FireFox', 'Safari', 'Edge'],
                    datasets: [{
                        label: 'Browser',
                        data: [<%= @browsers.dig(Browser::CHROME_ID).to_i %>, <%= @browsers.dig(Browser::FIREFOX_ID).to_i %>, <%= @browsers.dig(Browser::SAFARI_ID).to_i %>, <%= @browsers.dig(Browser::EDGE_ID).to_i %>],
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                        ],
                        borderColor: [
                            'rgb(255, 99, 132)',
                            'rgb(75, 192, 192)',
                            'rgb(54, 162, 235)',
                            'rgb(153, 102, 255)',
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
        //});
    </script>
    <!-- End Bar CHart -->

  </div>
</div>

app/views/home/_test_suite_scheduler_status.html.erb
<!-- Scheduler Status -->
<div class="card">
  <!--        <div class="filter">-->
  <!--          <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>-->
  <!--          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">-->
  <!--            <li class="dropdown-header text-start">-->
  <!--              <h6>Filter</h6>-->
  <!--            </li>-->
  <!--            <li><a class="dropdown-item" href="#">Today</a></li>-->
  <!--            <li><a class="dropdown-item" href="#">This Month</a></li>-->
  <!--            <li><a class="dropdown-item" href="#">This Year</a></li>-->
  <!--          </ul>-->
  <!--        </div>-->

  <div class="card-body pb-0">
    <h5 class="card-title">Test Suite Schedule Status</h5>

    <div id="schedulerPieChart"></div>

    <script>
        //document.addEventListener("DOMContentLoaded", () => {
            new ApexCharts(document.querySelector("#schedulerPieChart"), {
                series: [<%= @scheduler_running %>, <%= @scheduler_success %>, <%= @scheduler_ready %>, <%= @scheduler_error %>, <%= @scheduler_completed %>],
                chart: {
                    height: 250,
                    type: 'pie',
                    toolbar: {
                        show: true
                    }
                },
                labels: ['RUNNING', 'SUCCESS', 'READY', 'ERROR', 'COMPLETED']
            }).render();
        //});
    </script>

  </div>
</div><!-- End Scheduler Status -->

app/views/home/_test_suite_types.html.erb
<div class="card">
  <!--        <div class="filter">-->
  <!--          <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>-->
  <!--          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">-->
  <!--            <li class="dropdown-header text-start">-->
  <!--              <h6>Filter</h6>-->
  <!--            </li>-->

  <!--            <li><a class="dropdown-item" href="#">Today</a></li>-->
  <!--            <li><a class="dropdown-item" href="#">This Month</a></li>-->
  <!--            <li><a class="dropdown-item" href="#">This Year</a></li>-->
  <!--          </ul>-->
  <!--        </div>-->

  <div class="card-body pb-0">
    <h5 class="card-title">Suite Type</h5>

    <div id="suiteType"></div>

    <script>
        //document.addEventListener("DOMContentLoaded", () => {
        var chart = new ApexCharts(document.querySelector("#suiteType"), {
                series: [{
                    data: [<%= @manual_test_suites.count %>, <%= @automate_test_suites.count %>]
                }],
                chart: {
                    type: 'bar',
                    height: 250
                },
                plotOptions: {
                    bar: {
                        borderRadius: 4,
                        horizontal: false,
                    }
                },
                dataLabels: {
                    enabled: true,
                },

                xaxis: {
                    categories: ['Manual', 'Automate'],
                }
            }).render();
        //});
    </script>

  </div>
</div>

app/views/home/_total_summary.html.erb
<div class="col-xxl-4 col-md-6">
  <div class="card info-card sales-card">

    <!--            <div class="filter">-->
    <!--              <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>-->
    <!--              <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">-->
    <!--                <li class="dropdown-header text-start">-->
    <!--                  <h6>Filter</h6>-->
    <!--                </li>-->

    <!--                <li><a class="dropdown-item" href="#">Today</a></li>-->
    <!--                <li><a class="dropdown-item" href="#">This Month</a></li>-->
    <!--                <li><a class="dropdown-item" href="#">This Year</a></li>-->
    <!--              </ul>-->
    <!--            </div>-->

    <div class="card-body">
      <a href="<%= projects_url %>"><h5 class="card-title">Projects<span>| Till now</span></h5></a>

      <div class="d-flex align-items-center">
        <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
          <a href="<%= projects_url %>"><i class="bi bi-menu-button-wide"></i></a>
        </div>
        <div class="ps-3 pt-3">
          <a href="<%= projects_url %>"><h6><%= @projects.count %></h6></a>
          <span class="text-success small pt-1 fw-bold"></span>
          <span class="text-muted small pt-2 ps-1"></span>

        </div>
      </div>
    </div>

  </div>
</div>

<div class="col-xxl-4 col-md-6">
  <div class="card info-card revenue-card">

    <!--            <div class="filter">-->
    <!--              <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>-->
    <!--              <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">-->
    <!--                <li class="dropdown-header text-start">-->
    <!--                  <h6>Filter</h6>-->
    <!--                </li>-->

    <!--                <li><a class="dropdown-item" href="#">Today</a></li>-->
    <!--                <li><a class="dropdown-item" href="#">This Month</a></li>-->
    <!--                <li><a class="dropdown-item" href="#">This Year</a></li>-->
    <!--              </ul>-->
    <!--            </div>-->

    <div class="card-body">
      <a href="<%= environments_url %>"><h5 class="card-title">Environments<span>| Till now</span></h5></a>

      <div class="d-flex align-items-center">
        <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
          <a href="<%= environments_url %>"><i class="bi bi-cloud-plus"></i></a>
        </div>
        <div class="ps-3 pt-3">
          <a href="<%= environments_url %>"><h6><%= @environments.count %></h6></a>
          <span class="text-success small pt-1 fw-bold"></span>
          <span class="text-muted small pt-2 ps-1"></span>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="col-xxl-4 col-xl-12">

  <div class="card info-card customers-card">

    <!--            <div class="filter">-->
    <!--              <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>-->
    <!--              <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">-->
    <!--                <li class="dropdown-header text-start">-->
    <!--                  <h6>Filter</h6>-->
    <!--                </li>-->

    <!--                <li><a class="dropdown-item" href="#">Today</a></li>-->
    <!--                <li><a class="dropdown-item" href="#">This Month</a></li>-->
    <!--                <li><a class="dropdown-item" href="#">This Year</a></li>-->
    <!--              </ul>-->
    <!--            </div>-->

    <div class="card-body">
      <a href="<%= suites_path %>"><h5 class="card-title">Test Suites <span>| Till now</span></h5></a>

      <div class="d-flex align-items-center">
        <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
          <a href="<%= suites_path %>"><i class="bi bi-paperclip"></i></a>
        </div>
        <div class="ps-3 pt-3">
          <a href="<%= suites_path %>"><h6><%= @test_suites.count %></h6></a>
          <span class="text-danger small pt-1 fw-bold"><%= @test_cases.count + @manual_cases.count %></span>
          <span class="text-muted small pt-2 ps-1">Test cases</span>

        </div>
      </div>

    </div>
  </div>

</div>

app/views/home/documentation.html.erb
<%
  breadcrumb = { 'Home': root_url, 'Autoium - Documentation' => documentation_path }
  btn = []
%>
<%= render partial: 'common/breadcrumb', locals: { heading: 'Autoium - Documentation', breadcrumb: breadcrumb, action_btns: btn } %>

<section class="section">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Software Versions</h5>
          <div class="row">
            <div class="col-md-12">
              <p>
                Autoium is a versatile Java-based testing tool designed to simplify and enhance website testing using Selenium. With the capability to seamlessly operate in both console and GUI modes, Autoium empowers users to efficiently test and validate web applications. The intuitive GUI, built using Swing, provides a user-friendly interface, while the console mode allows for streamlined automation.
              </p>
              <!-- Table with stripped rows -->
              <%= render partial: 'software_versions/version_content'  %>
              <!-- End Table with stripped rows -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Chrome Extension</h5>
          <div class="row">
            <div class="col-md-12">
              <p>
                Check out the Autoium Chrome extension
                <a class="download-link" href="https://chromewebstore.google.com/detail/autoium/kdjmljenoekkdbclilboemighaafhgbl?hl=en-US&amp;utm_source=ext_sidebar" target="_blank">here</a>.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Drivers</h5>
          <div class="row">
            <div class="col-md-12">
              <p>
                To utilize Autoium effectively, you'll need to download the appropriate drivers:
              </p>
              <ul>
                <li>
                  <strong>Chrome Driver:</strong> Download the Chrome Driver <a class="download-link" href="https://sites.google.com/chromium.org/driver/" target="_blank">here</a>.
                  The path to the Chrome Driver can be configured via the Java tool's settings options.
                </li>
                <li>
                  <strong>Firefox Driver:</strong> Download the Firefox Driver <a class="download-link" href="https://github.com/mozilla/geckodriver/releases" target="_blank">here</a>.
                  Similarly, the path to the Firefox Driver can also be configured through the Java tool's settings options.
                </li>
                <li>
                  <strong>Edge Driver:</strong> Download the Edge Driver <a class="download-link" href="https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/?form=MA13LH#downloads" target="_blank">here</a>.
                  Configure the path to the Edge Driver using the Java tool's settings options.
                </li>
                <li>
                  <strong>Safari Driver:</strong> Safari and Safari Technology Preview each provide their own safaridriver executable. Safari’s executable is located at /usr/bin/safaridriver.
                  Configure the path to the Safari Driver using the Java tool's settings options.
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Setting up Autoium</h5>
          <div class="row">
            <div class="col-md-12">
              <p class="card-text">Get started by downloading the documentation PDF.</p>
              <p class="card-text">
                <a href="Autoium_executable_client_program.pdf" target="_blank" class="btn btn-primary">Download Documentation</a>
              </p>
              <div class="mt-3">
                <small class="text-muted">File size: 1MB | Last updated: February 22, 2024</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>

app/views/home/index.html.erb
<%= render partial: 'layouts/flash_message' %>
<section class="section dashboard">
  <div class="row">
    <!-- Left side columns -->
    <div class="col-lg-8">
      <div class="row">

        <!-- Total Summary -->
          <%= render 'home/total_summary' %>
        <!-- End Total Summary -->

        <div class="col-12">
        <%= render 'home/test_suite_scheduler_status' %>
        </div>

        <!-- Recent Schedulers -->
        <%= render 'home/recent_schedulers' %>
        <!-- End Recent Sales -->

      </div>
    </div><!-- End Left side columns -->

    <!-- Right side columns -->
    <div class="col-lg-4">

      <%= render 'home/test_suite_types' %>
      <%= render 'home/suite_browser_status' %>
      <%= render 'home/record_session_chart' %>

    </div><!-- End Right side columns -->

  </div>
</section>