config/routes.rb
Rails.application.routes.draw do

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :api do

    scope '/java', defaults: { format: :json } do
      post 'login_user', to: 'selenium#login_user'
      get 'get_scheduler', to: 'selenium#get_scheduler'
      get 'software_version', to: 'selenium#software_version'

      get 'get_projects', to: 'selenium#get_projects'
      get 'get_environments', to: 'selenium#get_environments'
      get 'get_environment', to: 'selenium#get_environment'
      get 'get_custom_command', to: 'selenium#get_custom_commands'

      get 'get_test_suites', to: 'selenium#get_test_suites'
      get 'get_test_suite', to: 'selenium#get_test_suite'
      post 'schedule_test_suite', to: 'selenium#schedule_test_suite'
      get 'unschedule_test_suite', to: 'selenium#unschedule_test_suite'

      get 'get_all_test_cases', to: 'selenium#get_test_cases'

      post 'create_result_suite', to: 'selenium#create_result_suite'
      post 'create_result_case', to: 'selenium#create_result_case'
      post 'update_result_suite', to: 'selenium#update_result_suite'
      post 'update_scheduler_status', to: 'selenium#update_scheduler_status'
      post 'upload_video', to: 'selenium#upload_video'
      post 'upload_screenshot', to: 'selenium#upload_screenshot'
    end

    namespace :v1 do
      resources :projects, only: [:index]

      resources :environments, only: [:index] do
        resources :test_suites, only: [:index, :create] do
          resources :test_cases, only: [:index, :create, :show, :update]
          resources :manual_test_cases, only: [:index, :create, :show, :update]
        end
        resources :custom_commands, only: [:index]
      end

      resources :users, only: [:index] do
        collection do
          post :login
          get :logout
        end
      end
    end
  end
  #end of api namespace

  resources :projects do
    collection do
      get :get_environments
    end
    resources :team_members do
      collection do
        post :assign_existing_member
      end
    end
  end

  resources :environments do
    member do
      get :login_details
      post :login_details

      get :git_branch_details
      post :git_branch_details
    end
    resources :custom_commands
    resources :test_plans do
      collection do
        get :flow_states
        get :hierarchy
        post :hierarchy
        get :load_plan_tree
      end
    end
    resources :test_roles

    resources :test_suites do
      member do
        get :assign_users
        post :assign_users
        get :remove_assign_suite
      end

      collection do
        get :import
        post :import
        get :automated
      end

      resources :test_cases do
        collection do
          get :selenium_custom_code
          get :export
        end
      end

      resources :manual_test_cases do
        member do
          delete :delete_attachment
        end
      end

      resources :schedulers do
        resources :results, only: [:index, :update] do
          member do
            get :status_override
          end
          collection do
            get :mark_as_demo_video
            get :download_results
            post :upload_recording
            get :delete_recording
          end
        end
      end

      resources :periodics
    end
  end

  resources :assign_suites, only: [:index] do
    collection do
      get :manual
    end
    member do
      get :manual_cases
    end
  end

  resources :manual_case_results do
  end

  resources :suite_reports, only:[:index, :show] do
    collection do
      get :automated
    end
  end
  resources :software_versions

  resource :session, only: [:create, :destroy] do
    collection do
      get :login
    end
  end

  resources :users, only: [:edit, :update] do
    member do
      get :settings
      post :settings
      delete :remove_invitation
      get :resend_invitation
    end
    collection do
      get :invite
      post :invite
      get :accept_invitation
      get :forgot_password
      post :forgot_password
      get :reset_password
    end
  end

  match "suites", to: "test_suites#suites", via: [:get]
  match "load_image", to: "file_handler#load_image", via: [:get]
  match "load_video", to: "file_handler#load_video", via: [:get]
  match "fetch-team-members", to: "team_members#fetch_team_members", via: [:get, :post]
  match "privacy_policy", to: "home#privacy_policy", via: :get
  match "documentation", to: "home#documentation", via: :get
  match "project_roles", to: "roles#project_roles", via: :get, as: "access_roles"

  # Defines the root path route ("/")
  #
  root "home#index"
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :get_environment
  before_action :get_test_suite
  before_action :get_scheduler
  before_action :get_result_suite, except: [:download_results]
  before_action :get_result_suites, only: [:download_results]
  def index
    redirect_to root_path, notice: 'Result has not captured yet for the schedule.' and return unless @result_suite.present?
    @result_cases = ResultCase.includes(:test_case).where(result_suite: @result_suite).order('test_cases.priority asc')
  end

  def update
    @result_case = ResultCase.where(id: params[:id]).take
    if request.xhr?
      @error = false
      @result_case.override_comment = params.dig("result_case", "override_comment")
      @result_case.rd_id = ResultsDictionary::STATUS[:SUCCESS]
      @result_case.override_status = true
      @result_case.mark_override = true
      @result_case.override_status_permanently = params.dig("result_case", "override_status_permanently")

      if @result_case.save
        flash[:success] = "Result Case sequence #{@result_case.test_case.priority} - override status has been marked successfully!"
        render js: "window.location.href =' #{environment_test_suite_scheduler_results_path(@environment, @test_suite, @scheduler)}'"
      else
        @error = true
        flash.now[:errors] = @result_case.errors.full_messages
      end
    end
  end
  def status_override
    @result_case = ResultCase.where(id: params[:id]).take
  end

  def mark_as_demo_video
    @test_suite.video_file = @result_suite.video_file
    @test_suite.save
    flash[:success] = "Test suite '#{@test_suite.name}' has been marked as a demo video successfully!"
    redirect_to environment_test_suite_scheduler_results_path(@environment, @test_suite, @scheduler)
  end

  def download_results
    generate_xls = PopulateExcel.new.generate_suite_results_xls(@result_suites)
    send_file generate_xls, type: "application/xlsx", filename: "#{@test_suite.name}-reults-#{Time.now.to_i}.xlsx"
  end

  def upload_recording
    _upload_file = params.dig(:result_suite, :upload_suite_recording)
    errors =  []
    errors << 'Video recording file cant be blank.' unless _upload_file.present?
    @result_suite.upload_suite_recording =  _upload_file

    if !errors.present? and @result_suite.save
      flash[:success] = "Recording has been uploaded successfully!"
    else
      flash[:errors] = [errors, @result_suite.errors.full_messages].flatten
    end
    redirect_to environment_test_suite_scheduler_results_path(@environment, @test_suite, @scheduler)
  end

  def delete_recording
    @result_suite.video_file = ''
    errors =  []
    errors << 'You are not authorize to delete recording.' unless @result_suite.user == Current.user
    if !errors.present? and @result_suite.save
      flash[:success] = "Recording has been deleted successfully!"
    else
      flash[:errors] = [errors, @result_suite.errors.full_messages].flatten
    end
    redirect_to environment_test_suite_scheduler_results_path(@environment, @test_suite, @scheduler)
  end

  private
  def get_environment
    @environment = Environment.where(id: params[:environment_id]).take
  end
  def get_test_suite
    @test_suite = @environment.test_suites.where(id: params[:test_suite_id]).take
  end

  def get_scheduler
    @scheduler = Scheduler.where(id: params[:scheduler_id]).take
  end

  def get_result_suites
    @result_suites =  ResultSuite.where(test_suite: @test_suite, scheduler: @scheduler).order('id DESC')
  end
  def get_result_suite
    @result_suite = get_result_suites.take
  end

end

app/helpers/results_helper.rb
module ResultsHelper
  def status_image(status)
    if status == 'SUCCESS'
      '<i class="bi bi-hand-thumbs-up-fill me-1 text-success" title="PASS" alt="PASS"></i>'
    elsif status == 'ERROR'
      '<i class="bi bi-hand-thumbs-down-fill me-1 text-danger" title="FAIL" alt="FAIL"></i>'
    elsif status == 'PENDING'
      '<i class="bi bi-truck me-1 text-secondary" title="PENDING" alt="PENDING"></i>'
    end
  end
end

app/views/results/_status_override_frm.html.erb
<%= form_with model: @result_case, url: environment_test_suite_scheduler_result_path(@environment, @test_suite, @scheduler, @result_case) , data: { turbo: false, remote: true } do |f| %>
<div id="error"></div>
<div class="row g-3">
  <div class="col-md-12">
    <%= f.label :override_comment, 'Override Comment', class: 'form-label fw-bold' %>
    <%= f.text_area :override_comment, class: 'form-control' %>
  </div>

  <div class="col-md-6 form-check form-switchs">
    <%= check_box_tag 'result_case[override_status_permanently]', class: 'form-check-input' %>
    <label class="form-check-label" for="result_case_override_status_permanently">Override error permanently</label>
  </div>

  <div class="col-md-12">
    <%= f.submit "Override Status", class: "btn btn-primary", data: { disable_with: "Please wait..." } %>
  </div>
</div>
<% end %>

app/views/results/index.html.erb
<%
  breadcrumb = {'Home': root_url, "#{@test_suite.name || 'Test Suite'}" => "#", 'Scheduler' => environment_test_suite_schedulers_path(@environment, @test_suite), 'Result' => '#' }
  btn = []
%>
<%= render partial: 'common/breadcrumb', locals: {heading: 'Test Suite Result', breadcrumb: breadcrumb, action_btns: btn} %>
<% result_dictionay = ResultsDictionary.status %>

<section class="section min-vh-100">
  <%= render partial: 'layouts/flash_message' %>
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <p class="card-title">Result Summary</p>
          <div class="row">
            <div class="col-2"><strong>Environment:</strong></div>
            <div class="col-4"><%= @environment.name %></div>

            <div class="col-2"><strong>Test Suite:</strong></div>
            <div class="col-4"><%= @test_suite.name %></div>

            <div class="col-2"><strong>Result Suite Status:</strong></div>
            <div class="col-4"><%= status_image(result_dictionay[@result_suite.rd_id].upcase.to_s).html_safe %></div>

            <div class="col-2"><strong>Result:</strong></div>
            <%
              _pass = @result_cases.collect{|result_case| result_case if result_case.rd_id == ResultsDictionary::STATUS.dig(:SUCCESS)}.compact
              _fail = @result_cases.collect{|result_case| result_case if result_case.rd_id == ResultsDictionary::STATUS.dig(:ERROR)}.compact
            %>
            <div class="col-4"><strong><span class="small text-danger">Fail: <%= _fail.count %></span> | <span class="small text-success">Pass: <%= _pass.count %></span></strong></div>

            <div class="col-2"><strong>Tester:</strong></div>
            <div class="col-4"><%= user_full_name(@result_suite.user) %></div>

            <div class="col-12 mt-2">
              <a href="<%= download_results_environment_test_suite_scheduler_results_path(@environment, @test_suite, @scheduler) %>" target="_blank" class="btn btn-warning" title="Download Results" title="Download Results"><i class="bi bi-download me-1"></i>Results</a>
              <% if @result_suite.video_file.present? %>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#videoModal" title="View Recording" title="View Recording"><i class="bi bi-eye me-1"></i> Recording</button>
                <a href="<%= @result_suite.video_file_url %>" target="_blank" class="btn btn-info" title="Download Recording" title="Download Recording"><i class="bi bi-cloud-download me-1"></i>Recording</a>

                <% if @result_suite.user == Current.user %>
                  <%= link_to(delete_recording_environment_test_suite_scheduler_results_path(@environment, @test_suite, @scheduler), class: 'btn btn-danger', title:"Delete Recording", alt:"Delete Recording",  data: {confirm: "Are you sure? You want delete the result suite recording." }) do %>
                    <i class="bi bi-trash me-1"></i>Recording
                  <% end %>
                <% end %>


                <% if @result_suite.video_file.present? and @test_suite.video_file != @result_suite.video_file %>
                  <a href="<%= mark_as_demo_video_environment_test_suite_scheduler_results_path(@environment, @test_suite, @scheduler) %>" target="_blank" class="btn btn-secondary"><i class="bi bi-file-earmark-check me-1"></i>Mark As Demo Video</a>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% if @result_suite.user == Current.user and !@result_suite.video_file.present? %>
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <%= form_with model: @result_suite, url: upload_recording_environment_test_suite_scheduler_results_path(@environment, @test_suite, @scheduler),  data: { turbo: false, remote: false }, html: { multipart: true }, method: :post do |f| %>
              <div class="row g-3 mt-1">
                <div class="col-md-6">
                  <%= f.file_field :upload_suite_recording, class: 'form-control' %>
                </div>
                <div class="col-md-6">
                  <%= f.submit "Upload Recording", class:"btn btn-primary" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <!-- Table with stripped rows -->
          <div class=table-responsive">
            <table class="table datatable mt-2" id="myTable">
              <thead>
              <tr>
                <th>Sq.</th>
                <th>Description</th>
                <th>Override</th>
                <th>Finish</th>
                <th>Status</th>
              </tr>
              </thead>
              <tbody>
              <% if @result_cases %>
                <% @result_cases.each do |result_case| %>
                  <tr>
                    <td><%= result_case.test_case.try(:priority) || 0 %></td>
                    <td>
                      <%= truncate result_case.error_description, length: 60 %>
                      <% if result_case.error_description.try(:length) > 60 %>
                        <span class="badge text-dark" data-bs-toggle="tooltip" data-bs-placement="bottom" title="<%= result_case.error_description %>"><i class="bi bi-info-circle me-1"></i></span>
                      <% end %>
                      <% if result_case.screenshot_file_location.present? %>
                        <%= link_to load_image_path(result_case: result_case.id) , title: 'View Error Screenshot', target:'_blank' do %>
                          <i class="bi bi-file-earmark-image text-dark"></i>
                        <% end %>
                      <% end %>
                      <% if result_case.rd_id != ResultsDictionary::STATUS[:SUCCESS] %>
                        <%= link_to "Override Status", status_override_environment_test_suite_scheduler_result_path(@environment, @test_suite, @scheduler, result_case), class: 'badge bg-info', remote: true %>
                      <% end %>
                    </td>
                    <td><%= result_case.override_comment  %></td>
                    <td><%= result_case.updated_at.strftime('%d-%m-%Y %H:%M')  %></td>
                    <td>
                      <%= status_image(result_dictionay[result_case.rd_id].upcase.to_s).html_safe %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
              </tbody>
            </table>
          </div>
          <!-- End Table with stripped rows -->
        </div>

      </div>
    </div>

  </div>
  </div>
</section>
<div class="modal fade" id="status-override-content" tabindex="-1" aria-hidden="true" style="display: none;">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title results-modal-title"></h5>
        <button type="button" class="btn-close" id="dismiss_model" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body status-override-frm-content">
      </div>
    </div>
  </div>
</div>

<% if @result_suite.video_file.present? %>
<div class="modal fade" id="videoModal" tabindex="-1" aria-hidden="true" style="display: none;">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title results-modal-title">Suite Result Recording</h5>
        <button type="button" class="btn-close" id="dismiss_model" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <video
          id="my-video"
          class="video-js"
          controls
          preload="auto"
          width="640"
          height="400"
          data-setup="{}"
        >
          <source src="<%= @result_suite.video_file_url%>" type="video/mp4" />
        </video>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/results/status_override.js.erb
$('.status-override-frm-content').html('<%= j(render partial: 'results/status_override_frm', format: :html) %>');
$('.results-modal-title').html('Override Result Test Case Status');
var user_assignment_modal = new bootstrap.Modal(document.getElementById('status-override-content'))
user_assignment_modal.show();

app/views/results/update.js.erb
<% if @error %>
$('#error').html('<%=j(render(partial: 'layouts/flash_message')) %>');
<% end %>