config/routes.rb
Rails.application.routes.draw do

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :api do

    scope '/java', defaults: { format: :json } do
      post 'login_user', to: 'selenium#login_user'
      get 'get_scheduler', to: 'selenium#get_scheduler'
      get 'software_version', to: 'selenium#software_version'

      get 'get_projects', to: 'selenium#get_projects'
      get 'get_environments', to: 'selenium#get_environments'
      get 'get_environment', to: 'selenium#get_environment'
      get 'get_custom_command', to: 'selenium#get_custom_commands'

      get 'get_test_suites', to: 'selenium#get_test_suites'
      get 'get_test_suite', to: 'selenium#get_test_suite'
      post 'schedule_test_suite', to: 'selenium#schedule_test_suite'
      get 'unschedule_test_suite', to: 'selenium#unschedule_test_suite'

      get 'get_all_test_cases', to: 'selenium#get_test_cases'

      post 'create_result_suite', to: 'selenium#create_result_suite'
      post 'create_result_case', to: 'selenium#create_result_case'
      post 'update_result_suite', to: 'selenium#update_result_suite'
      post 'update_scheduler_status', to: 'selenium#update_scheduler_status'
      post 'upload_video', to: 'selenium#upload_video'
      post 'upload_screenshot', to: 'selenium#upload_screenshot'
    end

    namespace :v1 do
      resources :projects, only: [:index]

      resources :environments, only: [:index] do
        resources :test_suites, only: [:index, :create] do
          resources :test_cases, only: [:index, :create, :show, :update]
          resources :manual_test_cases, only: [:index, :create, :show, :update]
        end
        resources :custom_commands, only: [:index]
      end

      resources :users, only: [:index] do
        collection do
          post :login
          get :logout
        end
      end
    end
  end
  #end of api namespace

  resources :projects do
    collection do
      get :get_environments
    end
    resources :team_members do
      collection do
        post :assign_existing_member
      end
    end
  end

  resources :environments do
    member do
      get :login_details
      post :login_details

      get :git_branch_details
      post :git_branch_details
    end
    resources :custom_commands
    resources :test_plans do
      collection do
        get :flow_states
        get :hierarchy
        post :hierarchy
        get :load_plan_tree
      end
    end
    resources :test_roles

    resources :test_suites do
      member do
        get :assign_users
        post :assign_users
        get :remove_assign_suite
      end

      collection do
        get :import
        post :import
        get :automated
      end

      resources :test_cases do
        collection do
          get :selenium_custom_code
          get :export
        end
      end

      resources :manual_test_cases do
        member do
          delete :delete_attachment
        end
      end

      resources :schedulers do
        resources :results, only: [:index, :update] do
          member do
            get :status_override
          end
          collection do
            get :mark_as_demo_video
            get :download_results
            post :upload_recording
            get :delete_recording
          end
        end
      end

      resources :periodics
    end
  end

  resources :assign_suites, only: [:index] do
    collection do
      get :manual
    end
    member do
      get :manual_cases
    end
  end

  resources :manual_case_results do
  end

  resources :suite_reports, only:[:index, :show] do
    collection do
      get :automated
    end
  end
  resources :software_versions

  resource :session, only: [:create, :destroy] do
    collection do
      get :login
    end
  end

  resources :users, only: [:edit, :update] do
    member do
      get :settings
      post :settings
      delete :remove_invitation
      get :resend_invitation
    end
    collection do
      get :invite
      post :invite
      get :accept_invitation
      get :forgot_password
      post :forgot_password
      get :reset_password
    end
  end

  match "suites", to: "test_suites#suites", via: [:get]
  match "load_image", to: "file_handler#load_image", via: [:get]
  match "load_video", to: "file_handler#load_video", via: [:get]
  match "fetch-team-members", to: "team_members#fetch_team_members", via: [:get, :post]
  match "privacy_policy", to: "home#privacy_policy", via: :get
  match "documentation", to: "home#documentation", via: :get
  match "project_roles", to: "roles#project_roles", via: :get, as: "access_roles"

  # Defines the root path route ("/")
  #
  root "home#index"
end

app/models/test_suite.rb
require 'csv'
class TestSuite < ApplicationRecord

    # -------------------------------------------------------------
    SUITE_FINAL_STATUS = 'Final'
    SUITE_DRAFT_STATUS = 'Draft'
    SUITE_STATUS = [SUITE_DRAFT_STATUS, SUITE_FINAL_STATUS]
    CHROME_PLATFORM = 'CHROME'
    WEB_PLATFORM = 'WEB'
    IMPORT_FILE_TYPE = ['text/csv','application/csv']

    # -------------------------------------------------------------
    belongs_to :user
    belongs_to :environment
    belongs_to :test_plan, optional: true
    belongs_to :base_suite, class_name: 'TestSuite', foreign_key: :base_suite_id, optional: true
    belongs_to :post_suite, class_name: 'TestSuite', foreign_key: :post_suite_id, optional: true
    has_many  :manual_cases, dependent: :destroy
    has_many  :test_cases, dependent: :destroy
    has_many :assign_manual_test_suites, dependent: :destroy
    has_many :schedulers, dependent: :destroy

    # -------------------------------------------------------------
    attr_accessor :platform
    attr_accessor :import_suite_cases

    # -------------------------------------------------------------
    validates :name, presence: true
    validates :short_description, presence: true, unless: proc { |suite| suite.platform == CHROME_PLATFORM }
    validate :check_presence_of_test_plan, if: proc { |suite| suite.platform == WEB_PLATFORM }
    validate :check_import_test_suite_file_type
    validate :check_import_test_suite_file_header

    # -------------------------------------------------------------
    before_save :populate_test_cases_import
    before_save :populate_default_short_desc_based_platform

    def include_base_post_suite
      [self.base_suite, self, self.post_suite].compact_blank
    end

    def is_manual_suite?
      !self.is_automated?
    end

    def video_file_url
      return '' unless self.video_file.present?

      project_id = self.environment.project.id
      FileUploader.retrieve(project_id, self.environment_id, 'videos', self.video_file)
    end

    private

    def check_presence_of_test_plan
      self.errors.add(:base, "Test plan can't be blank") unless self.test_plan.present?
    end
    def check_import_test_suite_file_type
      if self.import_suite_cases.present? and !TestSuite::IMPORT_FILE_TYPE.include?(self.import_suite_cases.content_type)
        errors.add(:base, "Please select a valid import file, only CSV type supported")
      end
    end

    def check_import_test_suite_file_header
      if self.import_suite_cases.present? and TestSuite::IMPORT_FILE_TYPE.include?(self.import_suite_cases.content_type)
        headers = CSV.open(self.import_suite_cases, :headers => true).read.headers
        if self.is_automated and !headers.include?("field_name")
          self.errors.add(:base, "CSV headers are invalid. It should have field_name for automate test suite.")
        elsif self.is_automated == false and !headers.include?("name")
          self.errors.add(:base, "CSV headers are invalid. It should have name for manual test suite.")
        end
      end
    end

    def populate_default_short_desc_based_platform
      if self.platform == TestSuite::CHROME_PLATFORM
        self.short_description ||= 'Created test suite through chrome.'
        self.status = TestSuite::SUITE_DRAFT_STATUS
      end
    end
    def populate_test_cases_import
      if self.import_suite_cases.present? and TestSuite::IMPORT_FILE_TYPE.include?(self.import_suite_cases.content_type)
        errors = []
        data_row = 1

        CSV.foreach(self.import_suite_cases, headers: true) do |row|
          test_case = row.to_h
          test_case = test_case.merge("priority" => (test_case["sequence"] || test_case["priority"]), user_id: self.user.id)
          test_case.delete("sequence")
          _test_case = TestCase.new(test_case)
          _test_case.test_suite = self
          if _test_case.valid?
            self.test_cases << _test_case
          else
            errors << "Row #{data_row} error: #{_test_case.errors.full_messages.join(',')}"
          end
          data_row = data_row + 1
        end

        if errors.present?
          self.errors.add(:base, errors)
          throw :abort
        end
      end
    end
end

app/controllers/api/v1/test_suites_controller.rb
class Api::V1::TestSuitesController < ApplicationApiController
  include CommonConcern
  def index
    if @environment
      @test_suites = @environment.test_suites.select(:id, :name, :is_automated).as_json
      render(json: { message: 'Test suites retrieved!', result: @test_suites, status: true }, status: :ok)
    else
      render(json: { message: 'Failed to retrieve test suites! Invalid environment', status: false }, status: :ok)
    end
  end

  def create
    @test_suite = TestSuite.new(test_suite_params)
    @test_suite.user = Current.user
    @test_suite.platform = TestSuite::CHROME_PLATFORM
    @test_suite.environment = @environment

    if @test_suite.save
      render json: { message: 'Test suite created!', status: true }, status: :ok
    else
      render json: { message: @test_suite.errors.full_messages.join(','), status: false }, status: :precondition_failed
    end
  end

  private

  def test_suite_params
    params.require(:test_suite).permit(:name, :short_description, :base_suite_id, :environment_id, :is_automated, :post_suite_id)
  end
end

app/controllers/test_suites_controller.rb
class TestSuitesController < ApplicationController

  # -------------------------------------------------------------
  before_action :user_projects_and_environments, only: [:index,:automated]
  before_action :get_environment
  before_action :get_test_suite, only: [:show, :edit, :update, :destroy, :assign_users, :remove_assign_suite]
  # -------------------------------------------------------------

  def index
    @section = 'suites'
    @test_suites = @environment.present? ? @environment.test_suites.where(is_automated: false) : []
  end

  def automated
    @section = 'suites'
    @test_suites = @environment.present? ? @environment.test_suites.where(is_automated: true) : []
    render :index
  end

  def suites
    redirect_to environment_test_suites_path(Current.user.prefer_environment) and return if Current.user.prefer_environment.present?
    flash[:notice] = 'Please save your preference first.'
    redirect_to settings_user_path(Current.user, redirect: 'suites')
  end

  def new
    @test_suite = TestSuite.new
  end

  def create
    @test_suite = TestSuite.new(test_suite_params)
    @test_suite.user = Current.user
    @test_suite.environment = @environment

    if @test_suite.save
      flash[:success] = 'Test Suite created successfully.'
      redirect_to environment_test_suites_url(@environment)
    else
      flash.now[:errors] = @test_suite.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @test_suite.update(test_suite_params)
      flash[:success] = 'Test suite updated successfully.'
      if request.xhr?
        render js: "window.location.href =' #{environment_test_suites_url(@environment)}'"
      else
        redirect_to environment_test_suites_url(@environment)
      end
    else
      flash.now[:errors] = @test_suite.errors.full_messages
      render :edit
    end
  end

  def destroy
    if Current.user == @test_suite.user or @environment.project.creator == Current.user
      if @test_suite.destroy
        flash[:success] = 'Suite deleted Successfully.'
      else
        flash[:errors] = @test_suite.errors.full_messages
      end
      redirect_to environment_test_suites_url(@environment)
    else
      redirect_to environment_test_suites_url(@environment), notice: "You are not allowed to delete the suite which are created by other user."
    end
  end

  def assign_users
    @error = false
    @assign_manual_test_suite = AssignManualTestSuite.new
    @schedulers = @test_suite.assign_manual_test_suites.order('id DESC')

    if request.post?
      user_ids = (assign_manual_test_suite_params[:assign_to] || []).map(&:to_i)
      test_suite_id = @test_suite.id #assign_manual_test_suite_params[:test_suite_id]
      if user_ids.empty? or @test_suite.manual_cases.empty?
        str = ''
        str << 'At-least one email must be selected.<br/>' if user_ids.empty?
        str << 'No manual case exist for test suite.' if @test_suite.manual_cases.empty?
        flash.now[:errors] = str
      else
        ## checking: if assignment exist for the user then dont create new entry into the system, only update the assignment cases
        user_assignment_exists = AssignManualTestSuite.where(assign_to: user_ids,
                                                        state: [AssignManualTestSuite::STATE_ASSIGN, AssignManualTestSuite::STATE_START],
                                                        test_suite_id: test_suite_id, browser: assign_manual_test_suite_params[:browser]
        ).collect(&:assign_to)
        error = ''
        [user_ids - user_assignment_exists].flatten.each do |user_id|
          ats =  AssignManualTestSuite.new(assign_to: user_id, test_suite_id: test_suite_id, browser: assign_manual_test_suite_params[:browser], assign_number: Time.now.to_i)
          ats.state = AssignManualTestSuite::STATE_ASSIGN
          if ats.save
          else
            error = ats.errors.full_messages.join(',')
            @error = true
            break
            #Rails.logger.info "Error: Test Suite Assign: #{ats.errors.full_messages.inspect}"
          end
        end
        if @error
          flash.now[:errors] = error
        else
          flash[:success] = 'Test suite assigned successfully!'
          redirect_to assign_users_environment_test_suite_url(@environment, @test_suite)
        end
      end
    end
  end

  def remove_assign_suite
    @assign_suite = AssignManualTestSuite.where(id: params[:suite]).take
    if @assign_suite.try(:state) == AssignManualTestSuite::STATE_ASSIGN
      @assign_suite.destroy
      flash[:success] = 'Assign suite successfully deleted.'
    else
      flash[:errors] = "#{@assign_suite.try(:state)} state test suite could not be deleted."
    end
    redirect_to assign_users_environment_test_suite_url(@environment, @test_suite)
  end

  def import
    if request.post?
      @test_suite = TestSuite.new(test_suite_import_params)
      errors = []
      errors << 'Import file must be present.' unless test_suite_import_params[:import_suite_cases].present?

      @test_suite.user = Current.user
      @test_suite.environment = @environment

      if @test_suite.save and errors.blank?
        flash[:success] = "Test suite '#{@test_suite.name}' & #{@test_suite.test_cases.count} test case(s) have been imported successfully."
        redirect_to environment_test_suites_path(@environment)
      else
        errors << @test_suite.errors.full_messages
        flash[:errors] = errors.flatten
      end
    else
      @test_suite = TestSuite.new
    end
  end

  private

  def get_environment
    @environment = Environment.where(id: params[:environment_id]).take
  end

  def get_test_suite
    @test_suite = @environment.test_suites.where(id: params[:id]).take
  end

  def test_suite_params
    params.require(:test_suite).permit(:name, :description, :short_description, :test_plan_id, :is_automated, :jira_id, :base_suite_id, :post_suite_id, :status, :is_stale)
  end

  def test_suite_import_params
    params.require(:test_suite).permit(:name, :short_description, :is_automated, :import_suite_cases, :dependency)
  end
  def assign_manual_test_suite_params
    params.require(:assign_manual_test_suite).permit(:test_suite_id, :browser, assign_to: [])
  end
end

app/helpers/test_suites_helper.rb
module TestSuitesHelper
end

app/views/test_suites/_assign_users_frm.html.erb
<%= form_with model: @assign_manual_test_suite, url: assign_users_environment_test_suite_path(@environment, @test_suite) , data: { turbo: false, remote: false } do |f| %>
  <div id="error"></div>
  <div class="row g-3">
    <div class="col-md-3">
      <%= f.label :test_suite, 'Test Suite*', class: 'form-label fw-bold' %>
      <%= f.select(:test_suite_id, options_for_select(@environment.test_suites.pluck(:name,:id), @test_suite.id), {include_blank: "Choose Test Suite"}, disabled: true, class: "form-control #{error_class(@test_suite, :test_suite_id)}") %>
    </div>

    <div class="col-md-3">
      <%= f.label :browser, 'Browser*', class: 'form-label fw-bold' %>
      <%= f.select(:browser, options_for_select(AssignManualTestSuite::BROWSERS), {}, class: "form-control #{error_class(@test_suite, :browser)}") %>
    </div>


    <div class="col-md-6">
      <label class="form-label fw-bold" for="user_email">Email:</label>
      <%= select_tag(:assign_to, options_for_select([]), name: 'assign_manual_test_suite[assign_to][]', id:'user_email', class: "form-control", multiple: true) %>
    </div>

    <div class="col-md-4">
      <%= f.submit "Assign Suite", class: "btn btn-primary", data: { disable_with: "Please wait..." } %>
    </div>
  </div>
<% end %>

app/views/test_suites/_form.html.erb
<%= render partial: 'layouts/flash_message' %>
<%
    _test_suites = TestSuite.where(environment_id: 3).pluck(:name,:id)
%>
<%= form_with model: @test_suite, url: @test_suite.new_record? ? environment_test_suites_path(@environment, @test_suite) : environment_test_suite_path(@environment, @test_suite), data: { turbo: false } do |f| %>
  <div class="row g-3">
    <div class="col-md-6">
      <%= f.label :test_plan, 'Test Plan*', class: 'form-label fw-bold' %>
      <%= f.select(:test_plan_id, options_for_select(@environment.test_plans.pluck(:name,:id), @test_suite.test_plan_id), {include_blank: "Choose Test Plan"}, class: "form-control #{error_class(@test_suite, :test_plan_id)}") %>
    </div>

    <div class="col-md-6">
      <%= f.label :is_automated, 'Suite Type', class: 'form-label fw-bold' %>
      <%= f.select(:is_automated, options_for_select({'Manual' => 0, 'Automated' => 1}, @test_suite.is_automated? ? 1 : 0), {}, class: "form-control", disabled: @test_suite.manual_cases.present?) %>
    </div>


    <div class="col-md-6">
      <%= f.label :name, 'Name*', class: 'form-label fw-bold' %>
      <%= f.text_field :name, placeholder: "Enter name", class: "form-control #{error_class(@test_suite, :name)}" %>
    </div>

    <div class="col-md-6">
      <%= f.label :jira_id, 'Jira Id', class: 'form-label fw-bold' %>
      <%= f.text_field :jira_id, placeholder: "Enter jira id", class: 'form-control' %>
    </div>

    <div class="col-md-6">
      <%= f.label :base_suite_id, 'Base Suite', class: 'form-label fw-bold' %>
      <%= f.select(:base_suite_id, options_for_select(_test_suites, @test_suite.base_suite_id), {include_blank: "Choose base suite"}, class: "form-control #{error_class(@test_suite, :base_suit_id)}") %>

    </div>
    <div class="col-md-6">
      <%= f.label :post_suite_id, 'Post Suite', class: 'form-label fw-bold' %>
      <%= f.select(:post_suite_id, options_for_select(_test_suites, @test_suite.post_suite_id), {include_blank: "Choose post suite"}, class: "form-control #{error_class(@test_suite, :post_suit_id)}") %>
    </div>
    <div class="col-md-12">
      <%= f.label :short_description, 'Short description (Max 255 chars)*', class: 'form-label fw-bold' %>
      <%= f.text_area :short_description, placeholder: "Enter short description", class: "form-control #{error_class(@test_suite, :short_description)}" %>
    </div>

    <div class="col-md-12">
      <%= f.label :description, 'Description', class: 'form-label fw-bold' %>
      <%= f.text_area :description, class: 'form-control tinymce' %>
    </div>

    <div class="col-md-6">
      <%= f.label :status, 'Suite Status', class: 'form-label fw-bold' %>
      <%= f.select(:status, options_for_select([[TestSuite::SUITE_DRAFT_STATUS,TestSuite::SUITE_DRAFT_STATUS], [TestSuite::SUITE_FINAL_STATUS,TestSuite::SUITE_FINAL_STATUS]], @test_suite.status), {}, class: "form-control") %>
    </div>

    <div class="col-md-6">
      <%= f.label :is_stale, 'Stale', class: 'form-label fw-bold' %>
      <%= f.select(:is_stale, options_for_select([['No', 0],['Yes', 1]]), {}, class: "form-control") %>
    </div>

    <div class="col-md-12">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/test_suites/_nav_tab.html.erb
<%
  _tabs = []
  _tabs << {label: 'Manual Suites', url: environment_test_suites_url(@environment), match: {controller: 'test_suites', action: 'index'}, badge:"bg-info", badge_name: 'M'}
  _tabs << {label: 'Automate Suites', url: automated_environment_test_suites_url(@environment), match: {controller: 'test_suites', action: 'automated'},badge:"bg-danger", badge_name: 'A'}
%>
<ul class="nav nav-tabs mt-2">
  <% _tabs.each do |suite| %>
    <li class="nav-item">
      <%= link_to(suite[:url], class: "nav-link #{'active' if suite[:match] == {controller: params[:controller], action: params[:action]}}") do %>
        <span class="badge rounded-pill <%= suite[:badge] %>"><%= suite[:badge_name] %></span>
        <%= suite[:label] %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/test_suites/_result_content.html.erb
<!-- Table with stripped rows -->
<table class="table datatable mt-2" id="myTable">
  <thead>
  <tr>
    <th>Name</th>
    <th>Short Description</th>
    <th>Test Plan</th>
    <th>Stale</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% if @test_suites %>
    <% @test_suites.each do |test_suite| %>
      <%
        if test_suite.is_automated?
          case_path =  environment_test_suite_test_cases_path(test_suite.environment, test_suite)
        else
          case_path =  environment_test_suite_manual_test_cases_path(test_suite.environment, test_suite)
        end
      %>
      <tr>
        <td><%= test_suite.name  %></td>
        <td>
          <%= truncate test_suite.short_description, length: 40 %>
          <% if (test_suite.short_description || '').length > 40 %>
            <span class="badge text-dark" data-bs-toggle="tooltip" data-bs-placement="bottom" title="<%= test_suite.short_description %>"><i class="bi bi-info-circle me-1"></i></span>
          <% end %>
        </td>
        <td><%= test_suite.test_plan.try(&:name)  %></td>
        <td><%= test_suite.is_stale ? "Yes" : "No" %></td>
        <td>
          <%= select_tag(
                "test_suite[status]",
                options_for_select(TestSuite::SUITE_STATUS, test_suite.status),
                class: 'form-control',
                data: {
                  remote: true,
                  url: environment_test_suite_path(@environment, test_suite),
                  method: 'put'
                },
                ) %>
        </td>
        <td>
          <%= link_to(case_path, title: 'Test Cases') do %>
            <i class="bi bi-briefcase"></i>
          <% end %>

          <% if test_suite.is_automated? %>
            <%= link_to(environment_test_suite_schedulers_path(test_suite.environment, test_suite), title: 'Schedule Now') do %>
              | <i class="bi bi-stopwatch"></i>
            <% end %>

            <%= link_to(environment_test_suite_periodics_path(test_suite.environment, test_suite), title: 'Preodic Schedule') do %>
              | <i class="bi bi-calendar-month"></i>
            <% end %>
          <% else %>
            <% if test_suite.manual_cases.present? %>
              <%= link_to(assign_users_environment_test_suite_path(test_suite.environment, test_suite), title: 'Assign suites to users', remote: false) do %>
                | <i class="bi bi-calendar-month"></i>
              <% end %>
            <% else %>
              <%= link_to "javascript:void(0)", title: 'Assign suites to users', data: { confirm: "There is no manual case(s) have created for the suite. Kindly create the suite first before user assignment." } do %>
                | <i class="bi bi-calendar-month"></i>
              <% end %>
            <% end %>
          <% end %>

          <%= link_to(edit_environment_test_suite_url(test_suite.environment, test_suite), title: 'Edit Suite') do %>
            | <i class="bi bi-pencil-fill"></i>
          <% end %>

          <%= link_to(environment_test_suite_url(test_suite.environment, test_suite), method: :delete, data: {confirm: 'Are you sure? It will delete all the associates records of it like Test cases etc.'}, title: 'Delete Suite') do %>
            | <i class="bi bi-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
<!-- End Table with stripped rows -->

app/views/test_suites/assign_users.html.erb
<%
  breadcrumb = {'Home': root_url, 'Environments' => environments_url, 'Test Suites' => environment_test_suites_url(@environment), 'Assign Test Suite' => '#' }
  btn = []
%>
<%= render partial: 'common/breadcrumb', locals: {heading: 'Assign Test Suite', breadcrumb: breadcrumb, action_btns: btn} %>

<section class="section min-vh-100">
  <div class="row">
    <div class="col-lg-12">
      <%= render partial: 'layouts/flash_message' %>
      <div class="card">
        <div class="card-body">
          <p class="card-title">Assign Test Suite</p>
          <%= render partial: 'test_suites/assign_users_frm' %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <p><strong>Environment:</strong> <%= @environment.name %> - <%= @environment.url %></p>
          <p><strong>Suite:</strong> <%= @test_suite.name %></p>

          <!-- Table with stripped rows -->
          <table class="table datatable mt-2" id="myTable">
            <thead>
            <tr>
              <th>ID</th>
              <th>Browser</th>
              <th>Assigned</th>
              <th>Tester</th>
              <th>State</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <% if @schedulers %>
              <% @schedulers.each do |scheduler| %>
                <tr>
                  <td><%= scheduler.assign_number %></td>
                  <td><%= scheduler.browser  %></td>
                  <td><%= scheduler.created_at.utc.strftime('%Y-%m-%d %H:%M')  %></td>
                  <td><%= scheduler.user.full_name  %></td>
                  <td><%= scheduler.state  %></td>
                  <td>
                    <% if scheduler.state == AssignManualTestSuite::STATE_FINISH %>
                      <%= ((scheduler.fail_case_count || 0) > 0 ? '<span class="badge rounded-pill bg-danger">Failed</span>' : '<span class="badge rounded-pill bg-success">Success</span>').html_safe %>
                    <% elsif scheduler.state == AssignManualTestSuite::STATE_ASSIGN  %>
                      <span class="badge rounded-pill bg-info">Ready</span>
                    <% elsif [AssignManualTestSuite::STATE_PROGRESS, AssignManualTestSuite::STATE_START].include?(scheduler.state)  %>
                      <span class="badge rounded-pill bg-primary">In-Progress</span>
                    <% end %>
                  </td>
                  <td>
                    <% if scheduler.state == AssignManualTestSuite::STATE_FINISH  %>
                      <%= link_to "Result", suite_report_path(scheduler), target: '_blank', class: 'btn small btn-outline-secondary' %>
                    <% end %>
                    <% if scheduler.state == AssignManualTestSuite::STATE_ASSIGN  %>
                      <%= link_to(remove_assign_suite_environment_test_suite_path(@environment, @test_suite, suite: scheduler.id), title: 'Removed') do %>
                        <i class="bi bi-trash"></i>
                      <% end %>
                    <% end %>

                  </td>
                </tr>
              <% end %>
            <% end %>
            </tbody>
          </table>
          <!-- End Table with stripped rows -->

        </div>
      </div>

    </div>
  </div>
</section>



<script>
    $('#user_email').select2({
        theme: "bootstrap",
        placeholder: "Search and select team member by name",
        width: '100%',
        multiple: true,
        ajax: {
            url: '<%= fetch_team_members_path(format: :json, format_id: true) %>',
            dataType: 'json'
        },
    })
</script>

app/views/test_suites/assign_users.js.erb
$('.test-assignment-user-content').html('<%= j(render partial: 'test_suites/assign_users_frm', locals: {}) %>');
var user_assignment_modal = new bootstrap.Modal(document.getElementById('test-assignment-user'))
user_assignment_modal.show();
<% if @error %>
$('#error').html('<%=j(render(partial: 'layouts/flash_message')) %>');
<% end %>

$('#test-assignment-user #user_email').select2({
    dropdownParent: $('#test-assignment-user'),
    theme: "bootstrap",
    placeholder: "Search and select team member by name",
    width: '100%',
    multiple: true,
    ajax: {
        url: '<%= fetch_team_members_path(format: :json, format_id: true) %>',
        dataType: 'json'
    },
})